# Generated by Django 2.1.5 on 2022-04-22 07:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 22, 13, 59, 46, 658457), verbose_name='date published'),
        ),
    ]
