# Generated by Django 2.1.5 on 2022-04-28 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220428_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 28, 18, 21, 19, 86259), verbose_name='date published'),
        ),
    ]
